// Canonical extended site-inspection form keys → DB columns `si_*` (one column per field).

export function formKeyToSiColumn(formKey) {
  if (!formKey || typeof formKey !== 'string') return null;
  const slug = formKey
    .replace(/\[(\d+)\]/g, '_$1')
    .replace(/\./g, '_')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .toLowerCase()
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
  return `si_${slug}`;
}

export const INSPECTION_FORM_FIELD_KEYS = [
  'jobDetails.inspectionCompany',
  'jobDetails.isMultiOccupancy',
  'jobDetails.consumerMains',
  'jobDetails.storey',
  'jobDetails.lifeSupportRequired',
  'jobDetails.licenseSelfie',
  'jobDetails.fullHousePhoto',
  'switchboard.meterPhoto',
  'switchboard.meterNumber',
  'switchboard.nmi',
  'switchboard.isCompliant',
  'switchboard.phases',
  'switchboard.biDirectionalMeter',
  'switchboard.neutralEarthPhoto',
  'switchboard.asbestosPresent',
  'switchboard.mainSwitchRatingAmps',
  'switchboard.pointOfAttachment',
  'switchboard.distanceTxToPOA',
  'switchboard.distancePOAToMSB',
  'switchboard.consumerMainsCableSize',
  'switchboard.consumerMainsCableType',
  'switchboard.mainsRunMethod',
  'switchboard.photoSwitchboardOn',
  'switchboard.photoSwitchboardOff',
  'switchboard.voltageReadingPhotos',
  'switchboard.inverterConnectedToMSB',
  'switchboard.spaceForSmartMeter',
  'switchboard.spareSpaceSolarBreaker',
  'switchboard.distanceInverterFromMSB',
  'subBoard.msbFeedsSubBoard',
  'subBoard.subBoardPOCPhoto',
  'inverterLocation.locationPhoto',
  'inverterLocation.requireACIsolator',
  'inverterLocation.mountingMethod',
  'inverterLocation.conduitRunDiscussed',
  'inverterLocation.notes',
  'battery.installingBattery',
  'monitoring.wifiAtLocation',
  'monitoring.strongReception',
  'monitoring.ethernetRunnable',
  'monitoring.spareRouterPort',
  'monitoring.wifiName',
  'monitoring.wifiPassword',
  'monitoring.distanceToEthernetPort',
  'existingSystem.existingSolar',
  'existingSystem.existingBattery',
  'roofProfile.roofHeightMeters',
  'roofProfile.safeAccess',
  'roofProfile.accessMethod',
  'roofProfile.panelCarryMethod',
  'roofProfile.edgeProtectionRequired',
  'roofProfile.edgeProtectionAvailable',
  'roofProfile.edgeProtectionMeters',
  'roofProfile.edgeProtectionPhoto',
  'roofProfile.roofMaterial',
  'roofProfile.roofConditionOK',
  'roofProfile.section1Pitch',
  'roofProfile.section1Photo',
  'roofProfile.section2Pitch',
  'roofProfile.section2Photo',
  'roofProfile.section3Pitch',
  'roofProfile.section3Photo',
  'roofProfile.anchorPoints',
  'roofProfile.skylightsPresent',
  'roofProfile.proposedDesignFits',
  'roofProfile.tiltsRequired',
  'roofProfile.tiltAngle',
  'roofProfile.spareTilesOnSite',
  'roofProfile.structureToMountModules',
  'roofProfile.anyShadingIssues',
  'roofProfile.dcCableRunMeters',
  'roofProfile.dcConduitMeters',
  'mudMap.mapPhoto',
  'mudMap.accessNotes',
  'shading.sources',
  'shading.other',
  'electrical.hazards',
  'electrical.other',
  'electrical.describeOther',
  'electrical.notes',
  'electrical.mitigations',
  'recommendations.count',
  'recommendations.summary',
  'recommendations.items[0]',
  'recommendations.items[1]',
  'recommendations.items[2]',
  'recommendations.items[3]',
  'recommendations.items[4]',
  'recommendations.items[5]',
  'recommendations.items[6]',
  'recommendations.items[7]',
  'recommendations.items[8]',
  'recommendations.items[9]',
  'mediaSummary.note',
];
